FROM nginx:latest as production
FROM node:12-alpine as compilation
LABEL maintainer="Mudi, Université de Rennes"
WORKDIR /app
COPY front/ .
RUN npm install &&\
	npm i -g @angular/cli@10.1.7 &&\
	ng build --prod
FROM production
WORKDIR /app
RUN rm -rf /usr/share/nginx/html/*
COPY --from=compilation /app/dist/tlcfront/ /usr/share/nginx/html/
# ADD server-confs/core.conf /etc/nginx/conf.d/core.conf
ADD server-confs/proxy.conf /etc/nginx/conf.d/proxy.conf
ADD server-confs/etherpad.conf /etc/nginx/conf.d/etherpad.conf
# ADD server-confs/backend.conf /etc/nginx/conf.d/backend.conf
ADD server-confs/phpmyadmin.conf /etc/nginx/conf.d/phpmyadmin.conf
ADD server-confs/prometheus.conf /etc/nginx/conf.d/prometheus.conf
ADD server-confs/grafana.conf /etc/nginx/conf.d/grafana.conf
ADD server-confs/munin.conf /etc/nginx/conf.d/munin.conf
EXPOSE 80