FROM fabric8/java-alpine-openjdk11-jre as production
FROM maven:3.8.6-openjdk-11-slim as compilation
WORKDIR /app/src/
COPY api/ .
RUN mvn package -DskipTests=true -Dquarkus.package.type=uber-jar
WORKDIR /app
FROM production
COPY --from=compilation /app/src/target/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar .
EXPOSE 8080
CMD ["java","-jar","tlcdemoApp-1.0.0-SNAPSHOT-runner.jar"]