doodle:
  usepad: true
  internalPadUrl: "http://etherpad:9001/"
#  externalPadUrl: "http://pad.midoodle.diverse-team.fr/"
  externalPadUrl: "http://pad.mwehbe.istic.univ-rennes1.fr//"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  organizermail: "ndiayeibrahim19@gmail.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  datasource:
    db-kind: mysql
    username: tlc
    password: tlc
    jdbc:
       url: jdbc:mysql://148.60.11.102:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
       #url: jdbc:mysql://db:3306/tlc
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: false
    baseline-on-migrate: false
#    database:
#      generation: none
#      globally-quoted-identifiers: true
  mailer:
    from: test@quarkus.io
#    host: smtp.sendgrid.net
    host: localhost
    port: 2525
#    port: 465
#    ssl: true

#    username: ""
#    password: ""
    mock: false
