doodle:
  usepad: true
  internalPadUrl: "http://localhost:9001/"
  externalPadUrl: "http://localhost:9001/"
  padApiKey: "19d89ca52bc0fa4f19d6325464d9d7a032649b9fa68c111514627081e2784b4a"
  # organizermail: "olivier.barais@gmail.com"
  organizermail: "malqabbani@live.com"
  tmpfolder: "/tmp/excelFiles"
quarkus:
  datasource:
    db-kind: mysql
    username: tlc
    password: tlc
    jdbc:
      url: jdbc:mysql://localhost:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris&createDatabaseIfNotExist=true
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
#    database:
#      generation: none
#      globally-quoted-identifiers: true
  mailer:
    from: test@quarkus.io
    host: smtp-relay.sendinblue.com
    port: 587
    username: "malqabbani@live.com"
    password: "bnOBKkgqhJtEyIG7"
    # mock: false

  mailer:
    from: test@quarkus.io
    host: mail
    port: 2525
#    host: smtp.sendgrid.net
#    port: 465
#    ssl: true

# #    username: ""
# #    password: ""
#     mock: false


